// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfc1dBMDkWvU7FjvtBCAuGwrpGnOo2YCc',
    appId: '1:466631438463:web:ad0be272407a92523ecf4a',
    messagingSenderId: '466631438463',
    projectId: 'kidesty-471cb',
    authDomain: 'kidesty-471cb.firebaseapp.com',
    storageBucket: 'kidesty-471cb.appspot.com',
    measurementId: 'G-3V5WW32RPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6dZgdENr2wB3MtStuKMmO1chu3netE0U',
    appId: '1:466631438463:android:ee7cf5169cf3c0d53ecf4a',
    messagingSenderId: '466631438463',
    projectId: 'kidesty-471cb',
    storageBucket: 'kidesty-471cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFk4EoK1DKun0-qEm5EzYUazEbp_2PJQ',
    appId: '1:466631438463:ios:26d256d1dae43f113ecf4a',
    messagingSenderId: '466631438463',
    projectId: 'kidesty-471cb',
    storageBucket: 'kidesty-471cb.appspot.com',
    iosBundleId: 'com.example.shabaniPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFk4EoK1DKun0-qEm5EzYUazEbp_2PJQ',
    appId: '1:466631438463:ios:26d256d1dae43f113ecf4a',
    messagingSenderId: '466631438463',
    projectId: 'kidesty-471cb',
    storageBucket: 'kidesty-471cb.appspot.com',
    iosBundleId: 'com.example.shabaniPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfc1dBMDkWvU7FjvtBCAuGwrpGnOo2YCc',
    appId: '1:466631438463:web:4b679fd072d973383ecf4a',
    messagingSenderId: '466631438463',
    projectId: 'kidesty-471cb',
    authDomain: 'kidesty-471cb.firebaseapp.com',
    storageBucket: 'kidesty-471cb.appspot.com',
    measurementId: 'G-6ZQDBT91Q2',
  );
}
