// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOAIEXULlZZm17yHdtbGelJ-b9GNNmnMk',
    appId: '1:795587654084:web:69f489558d5d7072777491',
    messagingSenderId: '795587654084',
    projectId: 'muki-2d1b6',
    authDomain: 'muki-2d1b6.firebaseapp.com',
    storageBucket: 'muki-2d1b6.appspot.com',
    measurementId: 'G-83GL0HS5GH',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJLn-0Z4esEv63fNF5QPdZDeZ130zlItg',
    appId: '1:795587654084:android:54fb1b2d0eee19b9777491',
    messagingSenderId: '795587654084',
    projectId: 'muki-2d1b6',
    storageBucket: 'muki-2d1b6.appspot.com',
  );

  static  FirebaseOptions ios =FirebaseOptions(
    apiKey: 'AIzaSyA51PKoC4Q_JSjsEZ_IwPpF5vPm_gOXjL0',
    appId: '1:795587654084:ios:24060e16d8cdd698777491',
    messagingSenderId: '795587654084',
    projectId: 'muki-2d1b6',
    storageBucket: 'muki-2d1b6.appspot.com',
    iosBundleId: 'com.example.shabaniPage',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA51PKoC4Q_JSjsEZ_IwPpF5vPm_gOXjL0',
    appId: '1:795587654084:ios:24060e16d8cdd698777491',
    messagingSenderId: '795587654084',
    projectId: 'muki-2d1b6',
    storageBucket: 'muki-2d1b6.appspot.com',
    iosBundleId: 'com.example.shabaniPage',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOAIEXULlZZm17yHdtbGelJ-b9GNNmnMk',
    appId: '1:795587654084:web:2f26e987b7ebce04777491',
    messagingSenderId: '795587654084',
    projectId: 'muki-2d1b6',
    authDomain: 'muki-2d1b6.firebaseapp.com',
    storageBucket: 'muki-2d1b6.appspot.com',
    measurementId: 'G-2ZDYXTGHD2',
  );
}
